- ignore: { name: "Avoid lambda" }
- ignore: { name: "Eta reduce" }
- ignore: { name: "Redundant lambda" }
- ignore: { name: "Use camelCase" }
- ignore: { name: "Use const" }
- ignore: { name: "Use curry" }
- ignore: { name: "Use fst" }
- ignore: { name: "Use snd" }
- ignore: { name: "Use tuple-section" }
- ignore: { name: "Use uncurry" }
