cabal-version:      2.4
name:               hscats
version:            0.1.0.0
author:             Liam Goodacre
maintainer:         goodacre.liam@gmail.com
extra-source-files:
    CHANGELOG.md
    README.md
    examples/README.md

library
    exposed-modules:
      Cats,
      Cats.Adjoint,
      Cats.Applicative,
      Cats.Associative,
      Cats.Binary,
      Cats.Cat,
      Cats.Category,
      Cats.Compose,
      Cats.Constructor,
      Cats.CrossProduct,
      Cats.Curry,
      Cats.Day,
      Cats.Delta,
      Cats.Do,
      Cats.Eval,
      Cats.Exponential,
      Cats.Flip,
      Cats.FromAdjoint,
      Cats.Functor,
      Cats.Hom,
      Cats.Id,
      Cats.Monad,
      Cats.MonoidObject,
      Cats.Monoidal,
      Cats.Opposite,
      Cats.Optics,
      Cats.Procompose,
      Cats.Profunctor,
      Cats.Span,
      Cats.Yoneda
    build-depends:
      , base
    hs-source-dirs: lib
    default-language: GHC2024
    default-extensions:
      AllowAmbiguousTypes,
      BlockArguments,
      FunctionalDependencies,
      ImplicitParams,
      NoImplicitPrelude,
      QualifiedDo,
      QuantifiedConstraints,
      RequiredTypeArguments,
      TypeAbstractions,
      TypeData,
      TypeFamilies,
      UndecidableInstances,
      UndecidableSuperClasses
    ghc-options: -O2 -Wall -Werror=orphans

test-suite hscats-test
    type: exitcode-stdio-1.0
    main-is: Main.hs
    other-modules:
      AdjunctionChecks,
      ApplicativeChecks,
      ApplicativeHelpersChecks,
      CoreLawChecks,
      CurryChecks,
      DayChecks,
      DayConversionChecks,
      DayInstances,
      DayUnsupported,
      MonoidalChecks,
      MonadChecks,
      OpticChecks,
      OppositeChecks,
      ProcomposeChecks,
      ProcomposeStructureChecks,
      ProcomposeUnsupported,
      ProductChecks,
      RecursionObjects,
      RecursionSchemes,
      SpanChecks
    build-depends:
      , base
      , hscats
    hs-source-dirs: test
    default-language: GHC2024
    default-extensions:
      AllowAmbiguousTypes,
      BlockArguments,
      FunctionalDependencies,
      ImplicitParams,
      NoImplicitPrelude,
      QualifiedDo,
      QuantifiedConstraints,
      RequiredTypeArguments,
      TypeAbstractions,
      TypeData,
      TypeFamilies,
      UndecidableInstances,
      UndecidableSuperClasses
    ghc-options: -O2 -Wall

test-suite hscats-examples
    type: exitcode-stdio-1.0
    main-is: Main.hs
    other-modules:
      CategoryExamples,
      FreeExamples,
      KanExamples,
      MonoidalSketches,
      RepresentableExamples
    build-depends:
      , base
      , hscats
    hs-source-dirs: examples
    default-language: GHC2024
    default-extensions:
      AllowAmbiguousTypes,
      BlockArguments,
      FunctionalDependencies,
      ImplicitParams,
      NoImplicitPrelude,
      QualifiedDo,
      QuantifiedConstraints,
      RequiredTypeArguments,
      TypeAbstractions,
      TypeData,
      TypeFamilies,
      UndecidableInstances,
      UndecidableSuperClasses
    ghc-options: -O2 -Wall
